name: meeting_place_control_plane_api
description: Control Plane API provides capabilities to enable the discovery of other participants to establish a connection and communicate securely.
version: 0.0.1-dev.1
publish_to: none

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  aws_dynamodb_api: ^2.0.0
  aws_kms_api: ^2.0.0
  aws_secretsmanager_api: ^2.0.0
  aws_sns_api: ^2.0.0
  aws_ssm_api: ^2.0.0
  aws_sts_api: ^2.0.0
  base_codecs: ^1.0.1
  convert: ^3.1.2
  crypto: ^3.0.6
  dart_jsonwebtoken: ^3.1.1
  didcomm: ^2.0.2
  dotenv: ^4.2.0
  elliptic: ^0.3.11
  http: ^1.3.0
  json_annotation: ^4.9.0
  logging: ^1.3.0
  lucid_validation: ^1.3.1
  meeting_place_core: ^0.0.1-dev.15
  meeting_place_mediator: ^0.0.1-dev.8
  mutex: ^3.1.0
  pointycastle: ^4.0.0
  proxy_recrypt: ^1.1.3
  redis: ^4.0.0
  shared_aws_api: ^2.0.2
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_static: ^1.1.3
  ssi: ^2.19.1
  uuid: ^4.5.1
  yaml: ^3.1.3

dev_dependencies:
  analyzer: ^7.7.1
  basic_utils: ^5.8.2
  build_runner: ^2.7.1
  cryptography: ^2.7.0
  dio: ^5.9.0
  json_serializable: ^6.11.1
  lints: ^5.0.0
  melos: ^7.1.0
  test: ^1.24.0


melos:
  scripts:
    pubget:
      exec: dart pub get

    analyze:
      exec: dart analyze .

    test:
      run: |
        melos run test-dart &&
        melos run coverage-report

    test-dart:
      description: Run tests in each dart package
      exec: dart run coverage:test_with_coverage
      dirExists: test

    coverage-report:
      run: >
        mkdir -p coverage

        find ./ -name "lcov.info" -path "*/coverage/lcov.info" -exec cat
        {} + > coverage/lcov.info
