didcommMessageBaseType: "https://affinidi.com/didcomm/protocols/mpx/1.0/"
acceptance:
  maximumRetries: 5

auth:
  accessTokenExpiryInMinutes: 15
  refreshTokenExpiryInMinutes: 720
  didResolverUrl: "https://dev.uniresolver.io"
  meetingPlaceRegistrationTokenExpiryInMinutes: 1440

deviceNotification:
  title: "Meeting Place"
  titleIncludeDev: true
  pushNotificationCustomKeyProperty: affinidiInfo
  maxPendingNotificationsToDeleteInBatch: 10

offer:
  mnemonicWordSeparator: ' '
  mnemonicWordCount: 5
  ttlInMinutesAfterValidUntil: 60

oob:
  oobUrlPath: "/v1/oob/__OOB_ID__"
  ttlInMinutes: 1440
